---
deployment:
  tasks:
    - export DEPLOYPATH=/home/digita28/public_html/
    - export SOURCEPATH=/home/digita28/repositories/scruma/scruma-web/out/
    - if [ ! -d "$SOURCEPATH" ]; then echo "SOURCEPATH ne postoji" && exit 1; fi
    - if [ ! -f "$SOURCEPATH/index.html" ]; then echo "index.html ne postoji u out" && exit 1; fi
    - /usr/bin/rsync -a --delete "$SOURCEPATH" "$DEPLOYPATH"
