---
deployment:
  tasks:
    - echo "CPANEL TASK START $(date)" > /home/digita28/public_html/cpanel-test.txt
    - /usr/bin/rsync -a --delete /home/digita28/repositories/scruma/scruma-web/out/ /home/digita28/public_html/
    - echo "DEPLOY DONE $(date)" > /home/digita28/public_html/deploy.txt
