# Generated by Django 5.2.11 on 2026-02-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("news", "Вести"),
                            ("notice", "Обавештења"),
                            ("sport", "Спортске вести"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("excerpt", models.TextField(blank=True, default="")),
                ("body", models.TextField(blank=True, default="")),
                ("image", models.ImageField(blank=True, null=True, upload_to="posts/")),
                ("link_url", models.URLField(blank=True, default="")),
                ("is_published", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="СЦ Рума", max_length=120)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="site/")),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                (
                    "hero_title",
                    models.CharField(default="Спортски центар Рума", max_length=160),
                ),
                ("hero_subtitle", models.TextField(blank=True, default="")),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                ("maps_embed_url", models.URLField(blank=True, default="")),
                (
                    "footer_text",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
