# Generated by Django 5.2.11 on 2026-02-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_footer_models_and_map_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Slug (путања)"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Наслов"
                    ),
                ),
                (
                    "subtitle",
                    models.TextField(blank=True, default="", verbose_name="Поднаслов"),
                ),
                (
                    "body",
                    models.TextField(blank=True, default="", verbose_name="Садржај"),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pages/",
                        verbose_name="Херо слика",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="SEO наслов",
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True, default="", max_length=260, verbose_name="SEO опис"
                    ),
                ),
                (
                    "show_in_nav",
                    models.BooleanField(
                        default=True, verbose_name="Прикажи у навигацији"
                    ),
                ),
                (
                    "nav_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Редослед у навигацији"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nav_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="announcement",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_bottom_text",
            field=models.CharField(blank=True, default="", max_length=220),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_logo",
            field=models.ImageField(blank=True, null=True, upload_to="site/"),
        ),
    ]
