# Generated by Django 5.2.11 on 2026-02-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_sitesettings_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="social_facebook_icon",
            field=models.ImageField(blank=True, null=True, upload_to="site/"),
        ),
    ]
