# Generated by Django 5.2.11 on 2026-02-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_sitesettings_social_facebook_icon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Обавештење",
                "verbose_name_plural": "Обавештења",
            },
        ),
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ["nav_order", "id"],
                "verbose_name": "Страница",
                "verbose_name_plural": "Странице",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-published_at"],
                "verbose_name": "Објава",
                "verbose_name_plural": "Објаве",
            },
        ),
        migrations.AlterModelOptions(
            name="sitesettings",
            options={
                "verbose_name": "Подешавања сајта",
                "verbose_name_plural": "Подешавања сајта",
            },
        ),
        migrations.AlterField(
            model_name="announcement",
            name="body",
            field=models.TextField(verbose_name="Садржај"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Креирано"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Наслов"),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(blank=True, default="", verbose_name="Садржај"),
        ),
        migrations.AlterField(
            model_name="post",
            name="excerpt",
            field=models.TextField(blank=True, default="", verbose_name="Сажетак"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="posts/", verbose_name="Слика"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Објављено"),
        ),
        migrations.AlterField(
            model_name="post",
            name="link_url",
            field=models.URLField(blank=True, default="", verbose_name="Линк"),
        ),
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Датум објаве"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=220, verbose_name="Наслов"),
        ),
        migrations.AlterField(
            model_name="post",
            name="type",
            field=models.CharField(
                choices=[
                    ("news", "Вести"),
                    ("notice", "Обавештења"),
                    ("sport", "Спортске вести"),
                ],
                max_length=20,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(
                blank=True, null=True, upload_to="site/", verbose_name="Фавикон"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_bottom_text",
            field=models.CharField(
                blank=True,
                default="",
                max_length=220,
                verbose_name="Доњи текст у футеру",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="site/", verbose_name="Лого у футеру"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_text",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Текст у футеру"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="site/", verbose_name="Херо слика"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_subtitle",
            field=models.TextField(
                blank=True, default="", verbose_name="Херо поднаслов"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="hero_title",
            field=models.CharField(
                default="Спортски центар Рума",
                max_length=160,
                verbose_name="Херо наслов",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="site/", verbose_name="Лого"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_name",
            field=models.CharField(
                default="СЦ Рума", max_length=120, verbose_name="Назив сајта"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="social_facebook_icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site/",
                verbose_name="Иконица за Фејсбук",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ажурирано"),
        ),
    ]
