# Generated by Django 5.2.11 on 2026-02-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_announcement_options_alter_page_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="seo_description",
            field=models.CharField(
                blank=True, default="", max_length=260, verbose_name="СЕО опис"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="seo_title",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="СЕО наслов"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Слаг (путања)"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="address",
            field=models.CharField(
                blank=True,
                default="Вељка Дугошевића 100, Рума",
                max_length=200,
                verbose_name="Адреса",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="maps_embed_url",
            field=models.CharField(
                blank=True,
                default="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2106.4186091167267!2d19.816897856951133!3d45.00865869273741!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x475babf00502b12f%3A0xa91ad9140edc7e6a!2z0KHQv9C-0YDRgtGB0LrQviDQv9C-0YHQu9C-0LLQvdC4INGG0LXQvdGC0LDRgA!5e1!3m2!1sen!2srs!4v1771758999050!5m2!1sen!2srs",
                max_length=600,
                verbose_name="Уграђена мапа (УРЛ)",
            ),
        ),
    ]
