# Generated by Django 5.2.11 on 2026-02-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_page_seo_description_alter_page_seo_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ажурирано"),
        ),
    ]
