# Generated by Django 5.2.11 on 2026-02-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_page_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="type",
            field=models.CharField(
                choices=[("notice", "Обавештења"), ("sport", "Спортске вести")],
                max_length=20,
                verbose_name="Тип",
            ),
        ),
    ]
